name: TechVoo
favicon: null
layout_spectrum: 0.6269760834984481
typography_spectrum: 0.30429271375760436
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5350955959875137
  lightness: 0.8504410868044943
  saturation: 0.4605055754072964
  rhythmicContrast: 0.9587282862048596
purpose: []
